### ISSUE TITLE
Cenário 3 atendido Parcialmente

### ISSUE THREAD

**Issue by eduardomarossi** [gabriellm1/WashMachineInterface#10]
Nenhum icone usa cor, nem botão.

Poderia ter usado cores intuitivas (verde pra iniciar, vermelho para parar) em botões.
O botão de iniciar e parar poderia ter uma legenda, a senhora pode não saber o símbolo

**Comment by gabriellm1** [comment]
A legenda estaria no painel que a tela da placa estaria inserida. Com as legendas a tela ficaria muito apertada.

**Comment by gabriellm1** [comment]
Agora os botões de iniciar é verde e o de parar vermelho.
