### ISSUE TITLE
Cuidado com o tipo Bool. Não existe booleano em C.

### ISSUE THREAD

**Issue by eduardomarossi** [gabriellm1/WashMachineInterface#11]
https://github.com/gabriellm1/WashMachineInterface/blob/9735cfb57894134ea04b1a45e00b479692b7a60e/src/main.c#L79-L81

Em C, não é definido o tipo booleano (verdadeiro ou falso) em seu padrão. 
Se você utilizar o Atmel Studio e clicar em Go To Definition em cima do Bool e nos valores 'true' e 'false'

Irá descobrir que nas bibliotecas tem:
```
typedef unsigned char           Bool; //!< Boolean.
#define true	1
#define false	0
```

Portanto, na verdade o Bool utilizado nao passa de um unsigned char (8-bits).
E qual o problema disso?

Bem, imagine que por algum motivo alguém faça o seguinte código.
```
Bool teste = false;
teste++;
Ou ainda teste = 3;
if(teste == true) { // ISTO FALHA pois true é 1
if(teste) { // Isto execute, pois C verifica se teste != 0
```

O código acima compila sem warnings e ainda te mascara do erro (true = 1). Por este motivo, este Bool existe por conveniência, mas pode te mascarar de alguns erros. 

Não está errado utiliza-lo, mas é desencorajado por muitos.

Pode ser trocado literalmente por
```
uint8_t teste = 0u;
if(teste) { // teste != 0
if(!teste) { // teste = 0
```

Neste caso, você sabe que são 8-bits, mas o que importa pra você é se é 0 (falso) ou diferente de zero (verdadeiro).

**Comment by gabriellm1** [comment]
Entendido. Nesse caso não vejo um possível problema, mas entendo que pra próximos projetos o que é melhor fazer.
