### ISSUE TITLE
Váriaveis globais sendo usadas apenas em uma função, poderia ser local

### ISSUE THREAD

**Issue by eduardomarossi** [gabriellm1/WashMachineInterface#2]
https://github.com/gabriellm1/WashMachineInterface/blob/9735cfb57894134ea04b1a45e00b479692b7a60e/src/main.c#L74

**Comment by gabriellm1** [comment]
A variável precisa ser global por que inicializar ela na função zeraria seu valor toda vez, sendo assim impossível detectar que o usuário pressionou 3 vezes para bloquear
