### ISSUE TITLE
Cenário 1 atendido parcialmente

### ISSUE THREAD

**Issue by eduardomarossi** [gabriellm1/WashMachineInterface#9]
Cenário 1 satisfaz parcialmente (é apenas apertar um botão pra travar/destravar tela, para travar tudo bem, mas o destrave é simples demais) e não para a máquina ao abrir porta, podendo ser um risco ao usuário ou a uma criança.

**Comment by gabriellm1** [comment]
Na verdade o bloqueio da terra ocorre através de 3 cliques no cadeado(botão de block), não apenas um pra travar e destravar. Agora no entanto caso a porta seja aberta durante a lavagem, ela é cancelada automaticamente e é avisado isso na tela.

**Comment by gabriellm1** [comment]
No último commit 7be6578 , além de fechar o issue 12 também foi melhorado o bloqueio. Antes para bloquear/desbloquear era necessário apertar 3x o cadeado sem restrição de tempo, podendo 3 cliques ocasionais realizar a ação. Agora o clique pro desbloqueio possui um time out, utilizando o periférico TC esses cliques precisam ser um seguido do outro pra de fato registrar a intenção de bloquear, melhorando a questão do cenário 1.

**Comment by eduardomarossi** [comment]
Parabéns!!!
